In [2]:
# import numpy
# import numpy as np

# Importamos la librería Numpy
import numpy as np # Creamos un alias de np a numpy

In [5]:
lista1 = [4, 5, 8, 9]
arr = np.array(lista1)
arr

array([4, 5, 8, 9])

In [7]:
# Ahora vamos a crear una matriz
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
aUnos = np.ones((4,3))
aUnos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.transpose(aUnos) # Transponer de filas a columnas

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
a = np.arange(12) # Esto es un vector
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
a = a.reshape(4,3) # Reestructuramos el vector a una matriz
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
a[3] # Accedemos al elemento de la

array([ 9, 10, 11])

In [21]:
a[1,2]

5

In [27]:
a = np.arange(10,40,2) #del 10 al 40 de 2 en 2, son 15 elementos
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [28]:
a[a>15] # Cuando ponemeos una condicion CAMBIA EL CONCEPTO 

array([16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [29]:
a[15] # esto nos da error

IndexError: index 15 is out of bounds for axis 0 with size 15

# Asignar Valores

In [32]:
a[1:3] = 1 # Asdignamos valores a elemntos del array
a

array([10,  1,  1, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [33]:
# Derefencia entre trabajar con referencias, vistas y listas

In [34]:
a = np.arange(5)
b = a # REFERENCIA
a

array([0, 1, 2, 3, 4])

In [35]:
b[0] = 5
a

array([5, 1, 2, 3, 4])

In [36]:
a[0] = 3
b

array([3, 1, 2, 3, 4])

In [37]:
c = a.copy() # COPIA
c[0] = 0
c

array([0, 1, 2, 3, 4])

In [38]:
a

array([3, 1, 2, 3, 4])

In [39]:
# Las vistas no comparten propiedades pero sí información. No cambián las propiedades pero si los valores.

In [40]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
aVista = a.view() # Utilizamos view para crear una VISTA
aVista.shape = (3,4)
aVista

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
aVista[0,0] = 30
a

array([30,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# 

In [44]:
x = np.arange(10)
x = x + 1 # Para crear un array de 1 al 10 le hemos sumado 1
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
np.sum(x)

55

In [46]:
np.prod(x)

3628800

In [48]:
np.mean(x) # Calculamos la media de los valores del array

5.5

In [49]:
np.min(x)

1

In [50]:
np.max(x)

10

In [51]:
# Operaciones por filas y columnas

In [52]:
x = np.random.random((2,4))
x

array([[0.84785086, 0.42554124, 0.71579971, 0.31470009],
       [0.20697828, 0.71675151, 0.42341768, 0.61168893]])

In [53]:
x.sum(axis=0) # esto suma los elementos de cada columna

array([1.05482914, 1.14229275, 1.13921738, 0.92638902])

In [55]:
x.sum(axis=1) # esto suma los elementos de cada fila

array([2.30389189, 1.95883639])