# PyTorch
### A gentle introduction to PyTorch

In [2]:
# Importamos módulos/librerías

import torch

import matplotlib.pyplot as plt
import numpy as np

The following line just checks if there is some GPU available and sets the `device` variable accordingly.

In [4]:
device = "cuda:0" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

Using device: cpu


## Introducing the basic element: *the tensor* 🔥💦🌬🗻

Tensors are the central object in pytorch. They can have a single dimension (vector), 2 dimensions (matrix), or n-dimensions (tensor). They also share a very similar interface to `ndarray`s of the popular `numpy` library. In PyTorch, tensors are represented with the [`Tensor`](https://pytorch.org/docs/stable/tensors.html) object.

Let's create our first pytorch tensors with some default values:

In [7]:
my_tensor = torch.Tensor([0., 1., 2.])
my_tensor

tensor([0., 1., 2.])

\Now that we have created a tensor, let's explore the "must know" attributes or properties that all pytorch tensors have:

In [8]:
print("The size of the tensor is:", my_tensor.size())

print("The type of the tensor is:", my_tensor.dtype)

print("Where is the tensor?", my_tensor.device)

print("Has the gradient property?", my_tensor.requires_grad)

The size of the tensor is: torch.Size([3])
The type of the tensor is: torch.float32
Where is the tensor? cpu
Has the gradient property? False


Note that pytorch tensors have the folowing default properties:
- The tensor is stored in CPU memory.
- By default numbers are stored as 32 bit float.

PyTorch tensors have a very similar interface to numpy's `ndarray`, let's see how to do some basic math operations with tensors:

In [9]:
double = 2 * my_tensor # myltiply a tensor by an scalar
half = my_tensor / 2
triple = double + my_tensor # opertions between tensors

print("Double", double)
print("Half:", half)
print("Triple", triple)

Double tensor([0., 2., 4.])
Half: tensor([0.0000, 0.5000, 1.0000])
Triple tensor([0., 3., 6.])


Pretty easy! right? As you can see, pytorch tensors can be manipulated using standard python operators, leading to cleaner code. But these operations can also be done directly using pytorch library functions ([reference](https://pytorch.org/docs/stable/torch.hztml)):

In [12]:
# Repeat the same operations from the code block above but using pytorch funcitions
double = torch.mul(2., my_tensor)
half = torch.div(my_tensor, 2.)
triple = torch.add(double, my_tensor)

print("Double:", double)
print("Half:", half)
print("Triple:", triple)

Double: tensor([0., 2., 4.])
Half: tensor([0.0000, 0.5000, 1.0000])
Triple: tensor([0., 3., 6.])


In the examples above, we have used a tensor created with some default values, but pytorch offers a wide variety of handy constructors to create our tensors. These are some of the most used ones, but the complete list of constructors can be found [here](https://pytorch.org/docs/stable/torch.html#creation-ops).  

In [15]:
# Create a tensor of 3x3 dimension with all values set to zero
z = torch.zeros(3, 3)
print("--> torch.zeros:\n\n", z)

# A tensor whose values are sampled from a uniform distribution on the [0, 1] range
u = torch.rand((3, 3)) # the shape of the tensor goes between parenthesis here
print("\n--> torch.rand:\n\n", u)

# A tensor whose values are sampled from a (0, 1) normal
n = torch.randn((3, 3))
print("\n--> torch.randn:\n\n", n)

# Returns a 2-D tensor with ones on the diagonal and zeros elsewhere
i = torch.eye(3, 3)
print("\n--> torch.eye:\n\n", i)

# Returns a 2-D tensor with ones 
o = torch.ones(3, 3)
print("\n--> torch.ones:\n\n", o)

--> torch.zeros:

 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

--> torch.rand:

 tensor([[0.7615, 0.7469, 0.3113],
        [0.5671, 0.7643, 0.6103],
        [0.3573, 0.0397, 0.7564]])

--> torch.randn:

 tensor([[ 2.3971,  0.3491,  0.8964],
        [ 1.2776, -0.1210,  1.4088],
        [ 0.2447,  0.7154, -1.2639]])

--> torch.eye:

 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

--> torch.ones:

 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
